# Generated by Django 2.2.5 on 2019-10-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('create_datetime', models.DateTimeField(auto_now=True)),
                ('update_datetime', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=256, null=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('head_image', models.CharField(max_length=128)),
                ('sexual_orientation', models.IntegerField()),
                ('country', models.IntegerField()),
                ('province', models.IntegerField()),
                ('city', models.IntegerField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
