# Generated by Django 2.2.5 on 2019-10-18 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=512)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, '我的存货'), (2, '我的展品'), (3, '我的货品')], default=0)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('is_online', models.BooleanField(default=True, help_text='物品是否上线')),
                ('is_delete', models.BooleanField(default=False, help_text='物品是否删除')),
                ('acquire_price', models.IntegerField(default=0, help_text='获得的价格')),
                ('stock', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=512)),
                ('intro', models.TextField(default='', help_text='更多介绍')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.Brand')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'db_table': 'stuff',
            },
        ),
    ]
