# Generated by Django 2.2.5 on 2019-10-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_auto_20191018_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
